on:
  workflow_dispatch:
    inputs:
      who_to_greet:
        required: true
        type: string

# env:
#   who_to_greet: George

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


  reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      who_to_greet: ${{ inputs.who_to_greet }}
    
  goodbye:
    runs-on: ubuntu-latest
    steps:  
      - name: A job to say goodbye
        run: echo "Goodbye ${{ inputs.who_to_greet }}!"
        shell: bash
