name: Issue metrics report

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 15 5 * * 1-5

permissions:
  issues: read
  pull-requests: read


jobs:
  issue-metrics-report:
    uses: George-Smirnoff/reusable-workflows/.github/workflows/RW_issue_metrics.yml@0841db265a45d7173ed7b03f960d45155d7012af
    with:
      repository_path: ${{ github.repository }}