on:
  workflow_call:
    inputs:
      who_to_greet:
        required: true
        type: string
  push:
    branches:
      - main


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo "Hello ${{ inputs.who_to_greet }}!"
        shell: bash