name: Reusable workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      aws_credentials:
        required: true

jobs:
  aws_creds:
    name: AWS credentials
    runs-on: ubuntu-latest
    steps:
      - name: Masking inputs
        run: |
          echo "::add-mask::${{ secrets.aws_credentials }}"

      - name: Parse Credentials
        id: parse_credentials
        run: |
          echo ${{ secrets.aws_credentials }} | sed 's/./& /g'


          CREDS_CLEAN=${{ secrets.aws_credentials }}
          # Use sed to extract the AWS credentials and assign them to variables
          INPUT_AWS_ACCESS_KEY_ID=$(echo "$CREDS_CLEAN" | sed -n 's/export AWS_ACCESS_KEY_ID="\([^"]*\)"/\1/p')
          INPUT_AWS_SECRET_ACCESS_KEY=$(echo "$CREDS_CLEAN" | sed -n 's/export AWS_SECRET_ACCESS_KEY="\([^"]*\)"/\1/p')
          INPUT_AWS_SESSION_TOKEN=$(echo "$CREDS_CLEAN" | sed -n 's/export AWS_SESSION_TOKEN="\([^"]*\)"/\1/p')

          echo ::add-mask::$INPUT_AWS_ACCESS_KEY_ID
          echo ::add-mask::$INPUT_AWS_SECRET_ACCESS_KEY
          echo ::add-mask::$INPUT_AWS_SESSION_TOKEN
          echo "aws_access_key_id=$INPUT_AWS_ACCESS_KEY_ID" >> $GITHUB_OUTPUT
          echo "aws_secret_access_key=$INPUT_AWS_SECRET_ACCESS_KEY" >> $GITHUB_OUTPUT
          echo "aws_session_token=$INPUT_AWS_SESSION_TOKEN" >> $GITHUB_OUTPUT