name: Terraform Apply

on:
  push:
    branches:
      - main # Change this to the default branch name of your repository
  workflow_dispatch:


jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.7

      # - name: Configure AWS Credentials
      # uses: aws-actions/configure-aws-credentials@v2
      # with:
      #   aws-region: me-south-1
      #   aws-access-key-id: ${{ secrets.aws_access_key_id }}
      #   aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
      #   aws-session-token: ${{ secrets.aws_session_token }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform_pull_private_repo

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform_pull_private_repo

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform_pull_private_repo

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      # Optional: To destroy resources after use
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
