

name: Restart K8s resources

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: Namespace of the resource. Use 'all' to restart pods in the entire Kubernetes cluster
        default: ""
        required: true
      resource_type:
        description: Type of the resource to restart. If empty, restart all resources
        default: ""
        required: false
      label:
        description: 'Label to filter resources for restart. For example: app=myapp'
        default: ""
        required: false
      environment:
        description: Provide environment (staging or production)
        default: "staging"
        type: choice
        required : true
        options: 
        - staging
        - production
        - ubuntu-latest


# env:
#   who_to_greet: George

jobs:
  run_reusable_workflow_ubuntu:
    if: ${{ inputs.environment == 'ubuntu-latest' }}
    uses: ./.github/workflows/RW_restart_pods.yaml
    environment: "${{ inputs.environment }}"
    with:
      namespace: ${{ inputs.namespace }}
      resource_type: ${{ inputs.resource_type }}
      label: ${{ inputs.label }}
      environment: ${{ inputs.environment }}
    secrets:
      aws_access_key_id: ${{ secrets.PRODUCTION_CI_DEPLOYER_ACCESS_KEY }}
      aws_secret_access_key: ${{ secrets.PRODUCTION_CI_DEPLOYER_ACCESS_SECRET }}

  run_reusable_workflow_staging:
    if: ${{ inputs.environment == 'staging' }}
    uses: ./.github/workflows/RW_restart_pods.yaml
    with:
      namespace: ${{ inputs.namespace }}
      resource_type: ${{ inputs.resource_type }}
      label: ${{ inputs.label }}
      environment: ${{ inputs.environment }}
    secrets:
      aws_access_key_id: ${{ secrets.PRODUCTION_CI_DEPLOYER_ACCESS_KEY }}
      aws_secret_access_key: ${{ secrets.PRODUCTION_CI_DEPLOYER_ACCESS_SECRET }}

  run_reusable_workflow_production:
    if: ${{ inputs.environment == 'production' }}
    uses: ./.github/workflows/RW_restart_pods.yaml
    with:
      namespace: ${{ inputs.namespace }}
      resource_type: ${{ inputs.resource_type }}
      label: ${{ inputs.label }}
      environment: ${{ inputs.environment }}
    secrets:
      aws_access_key_id: ${{ secrets.PRODUCTION_CI_DEPLOYER_ACCESS_KEY }}
      aws_secret_access_key: ${{ secrets.PRODUCTION_CI_DEPLOYER_ACCESS_SECRET }}
